import { pgTable, uuid, varchar, integer, text, timestamp, boolean, decimal, index, uniqueIndex, jsonb, pgEnum } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { panelist } from "./panelists";

// Enums for status fields
export const surveyStatusEnum = pgEnum("survey_status_enum", ["available", "draft", "archived", "closed", "pending"]);
export const invitationStatusEnum = pgEnum("invitation_status_enum", ["sent", "opened", "clicked", "qualified", "expired"]);
export const completionStatusEnum = pgEnum("completion_status_enum", ["started", "completed", "submitted", "disqualified"]);

// Survey metadata cache - surveys fetched from external survey portal
export const survey = pgTable("surveys", {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    externalId: varchar("external_id", { length: 100 }).notNull(),
    sourcePortal: varchar("source_portal", { length: 100 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    description: text("description"),
    points: integer("points").notNull().default(100),
    estimatedMinutes: integer("estimated_minutes").notNull().default(5),
    category: varchar("category", { length: 100 }).notNull(),
    tags: jsonb("tags"),
    status: surveyStatusEnum("status").notNull().default("available"),
    isActive: boolean("is_active").default(true),
    priority: integer("priority").default(0),
    targetAudience: text("target_audience"),
    screeningQuestions: jsonb("screening_questions"),
    qualifications: jsonb("qualifications"),
    excludedPanelists: jsonb("excluded_panelists"),
    maxCompletions: integer("max_completions"),
    currentCompletions: integer("current_completions").default(0),
    panelQuota: integer("panel_quota"),
    completionRate: decimal("completion_rate", { precision: 5, scale: 2 }).default("0.00"),
    averageRating: decimal("average_rating", { precision: 3, scale: 2 }).default("0.00"),
    averageCompletionTime: integer("average_completion_time"),
    qualityScore: integer("quality_score").default(100),
    isPublic: boolean("is_public").default(true),
    requiresApproval: boolean("requires_approval").default(false),
    autoAssign: boolean("auto_assign").default(false),
    allowReentries: boolean("allow_reentries").default(false),
    externalUrl: varchar("external_url", { length: 500 }),
    availableFrom: timestamp("available_from"),
    availableUntil: timestamp("available_until"),
    isDeleted: boolean("is_deleted").default(false),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    deletedAt: timestamp("deleted_at"),
    archivedAt: timestamp("archived_at"),
}, (table) => [
    uniqueIndex("surveys_unique_external_idx").on(table.sourcePortal, table.externalId),
    index("surveys_status_idx").on(table.status),
    index("surveys_active_idx").on(table.isActive),
    index("surveys_category_idx").on(table.category),
    index("surveys_priority_idx").on(table.priority),
    index("surveys_points_idx").on(table.points),
    index("surveys_public_idx").on(table.isPublic),
    index("surveys_quality_idx").on(table.qualityScore),
    index("surveys_completion_rate_idx").on(table.completionRate),
    index("surveys_available_public_idx").on(table.status, table.isPublic, table.isActive),
    index("surveys_targeting_idx").on(table.category, table.points, table.isActive),
    index("surveys_created_by_idx").on(table.createdBy),
    index("surveys_deleted_at_idx").on(table.deletedAt),
]);

export const surveyQuestion = pgTable("survey_questions", {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    surveyId: uuid("survey_id").notNull().references(() => survey.id, { onDelete: "cascade" }),
    externalQuestionId: varchar("external_question_id", { length: 100 }),
    type: varchar("type", { length: 50 }).notNull(),
    question: text("question").notNull(),
    description: text("description"),
    isScreening: boolean("is_screening").default(false),
    screeningCriteria: jsonb("screening_criteria"),
    options: jsonb("options"),
    required: boolean("required").default(true),
    order: integer("order").notNull(),
    validation: text("validation"),
    disqualifyValues: jsonb("disqualify_values"),
    isDeleted: boolean("is_deleted").default(false),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("survey_questions_survey_id_idx").on(table.surveyId),
    index("survey_questions_type_idx").on(table.type),
    index("survey_questions_screening_idx").on(table.isScreening),
    index("survey_questions_order_idx").on(table.surveyId, table.order),
    index("survey_questions_external_id_idx").on(table.externalQuestionId),
    index("survey_questions_created_by_idx").on(table.createdBy),
    index("survey_questions_deleted_at_idx").on(table.deletedAt),
]);

export const surveyInvitation = pgTable("survey_invitations", {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    surveyId: uuid("survey_id").notNull().references(() => survey.id, { onDelete: "cascade" }),
    panelistId: uuid("panelist_id").notNull().references(() => panelist.id, { onDelete: "cascade" }),
    invitationType: varchar("invitation_type", { length: 32 }).notNull().default("targeted"),
    invitationMethod: varchar("invitation_method", { length: 32 }).notNull().default("email"),
    status: invitationStatusEnum("status").notNull().default("sent"),
    targetingReason: text("targeting_reason"),
    qualificationStatus: varchar("qualification_status", { length: 32 }),
    disqualificationReason: text("disqualification_reason"),
    sentAt: timestamp("sent_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    openedAt: timestamp("opened_at"),
    clickedAt: timestamp("clicked_at"),
    qualifiedAt: timestamp("qualified_at"),
    expiresAt: timestamp("expires_at"),
    ipAddress: varchar("ip_address", { length: 45 }),
    userAgent: text("user_agent"),
    referrerUrl: varchar("referrer_url", { length: 500 }),
    isDeleted: boolean("is_deleted").default(false),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("survey_invitations_survey_id_idx").on(table.surveyId),
    index("survey_invitations_panelist_id_idx").on(table.panelistId),
    index("survey_invitations_status_idx").on(table.status),
    index("survey_invitations_qualification_idx").on(table.qualificationStatus),
    index("survey_invitations_sent_at_idx").on(table.sentAt),
    index("survey_invitations_expires_at_idx").on(table.expiresAt),
    index("survey_invitations_survey_status_idx").on(table.surveyId, table.status),
    index("survey_invitations_panelist_status_idx").on(table.panelistId, table.status),
    uniqueIndex("survey_invitations_unique_idx").on(table.surveyId, table.panelistId),
    index("survey_invitations_created_by_idx").on(table.createdBy),
    index("survey_invitations_deleted_at_idx").on(table.deletedAt),
]);

export const surveyTransaction = pgTable("survey_transactions", {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    panelistId: uuid("panelist_id").notNull().references(() => panelist.id, { onDelete: "cascade" }),
    surveyId: uuid("survey_id").notNull().references(() => survey.id, { onDelete: "cascade" }),
    status: completionStatusEnum("status").notNull().default("started"),
    awardedPoints: integer("awarded_points").default(0),
    bonusPoints: integer("bonus_points").default(0),
    qualityRating: integer("quality_rating"),
    timeSpentSeconds: integer("time_spent_seconds"),
    startedAt: timestamp("started_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    completedAt: timestamp("completed_at"),
    submittedAt: timestamp("submitted_at"),
    isDeleted: boolean("is_deleted").default(false),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("survey_completions_survey_id_idx").on(table.surveyId),
    index("survey_completions_panelist_id_idx").on(table.panelistId),
    index("survey_completions_status_idx").on(table.status),
    index("survey_completions_completed_at_idx").on(table.completedAt),
    index("survey_completions_quality_idx").on(table.qualityRating),
    uniqueIndex("survey_completions_unique_idx").on(table.surveyId, table.panelistId),
    index("survey_completions_created_by_idx").on(table.createdBy),
    index("survey_completions_deleted_at_idx").on(table.deletedAt),
]);

export const surveyTransactionDetails = pgTable("survey_transaction_details", {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    surveyId: uuid("survey_id").notNull(),
    panelistId: uuid("panelist_id").notNull(),
    deviceType: varchar("device_type", { length: 50 }),
    browserInfo: text("browser_info"),
    ipAddress: varchar("ip_address", { length: 45 }),
    location: text("location"),
    userAgent: text("user_agent"),
    referrerUrl: varchar("referrer_url", { length: 500 }),
    utmSource: varchar("utm_source", { length: 100 }),
    utmMedium: varchar("utm_medium", { length: 100 }),
    utmCampaign: varchar("utm_campaign", { length: 100 }),
    metadata: jsonb("metadata"),
    isDeleted: boolean("is_deleted").default(false),
    createdBy: uuid("created_by"),
    updatedBy: uuid("updated_by"),
    createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("survey_transaction_details_survey_id_idx").on(table.surveyId),
    index("survey_transaction_details_panelist_id_idx").on(table.panelistId),
    index("survey_transaction_details_device_type_idx").on(table.deviceType),
    index("survey_transaction_details_ip_address_idx").on(table.ipAddress),
    index("survey_transaction_details_utm_source_idx").on(table.utmSource),
    index("survey_transaction_details_created_by_idx").on(table.createdBy),
    index("survey_transaction_details_deleted_at_idx").on(table.deletedAt),
]);
// ...existing code for surveyLogic, surveyAvailability, etc. can be similarly refactored if needed...