CREATE INDEX "idx_session_user_id" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_session_expires_at" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_session_token" ON "sessions" USING btree ("token");--> statement-breakpoint
CREATE INDEX "idx_user_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_user_user_type" ON "users" USING btree ("user_type");--> statement-breakpoint
CREATE INDEX "idx_user_is_active" ON "users" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_user_status" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_user_created_at" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_user_referral_code" ON "users" USING btree ("referral_code");--> statement-breakpoint
CREATE INDEX "idx_user_user_type_active" ON "users" USING btree ("user_type","is_active");--> statement-breakpoint
CREATE INDEX "idx_user_status_active" ON "users" USING btree ("status","is_active");--> statement-breakpoint
CREATE INDEX "idx_survey_is_active" ON "surveys" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_survey_created_at" ON "surveys" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_user_id" ON "survey_transactions" USING btree ("panelist_id");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_survey_id" ON "survey_transactions" USING btree ("survey_id");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_status" ON "survey_transactions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_started_at" ON "survey_transactions" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_completed_at" ON "survey_transactions" USING btree ("completed_at");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_user_survey" ON "survey_transactions" USING btree ("panelist_id","survey_id");--> statement-breakpoint
CREATE INDEX "idx_survey_transaction_user_status" ON "survey_transactions" USING btree ("panelist_id","status");--> statement-breakpoint
CREATE INDEX "idx_panelist_point_panelist_id" ON "panelist_points" USING btree ("panelist_id");--> statement-breakpoint
CREATE INDEX "idx_panelist_point_current_points" ON "panelist_points" USING btree ("current_points");--> statement-breakpoint
CREATE INDEX "idx_panelist_point_pending_points" ON "panelist_points" USING btree ("pending_points");--> statement-breakpoint
CREATE INDEX "idx_points_transaction_panelist_id" ON "points_transactions" USING btree ("panelist_id");--> statement-breakpoint
CREATE INDEX "idx_points_transaction_type" ON "points_transactions" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_points_transaction_created_at" ON "points_transactions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_points_transaction_reference" ON "points_transactions" USING btree ("reference_type","reference_id");--> statement-breakpoint
CREATE INDEX "idx_points_transaction_panelist_type" ON "points_transactions" USING btree ("panelist_id","type");--> statement-breakpoint
CREATE INDEX "idx_cta_click_visitor_id" ON "cta_clicks" USING btree ("visitor_id");--> statement-breakpoint
CREATE INDEX "idx_cta_click_session_id" ON "cta_clicks" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_cta_click_timestamp" ON "cta_clicks" USING btree ("clicked_at");--> statement-breakpoint
CREATE INDEX "idx_cta_click_button" ON "cta_clicks" USING btree ("button_location");--> statement-breakpoint
CREATE INDEX "idx_page_visit_visitor_id" ON "page_visits" USING btree ("visitor_id");--> statement-breakpoint
CREATE INDEX "idx_page_visit_session_id" ON "page_visits" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_page_visit_timestamp" ON "page_visits" USING btree ("visited_at");--> statement-breakpoint
CREATE INDEX "idx_page_visit_fingerprint" ON "page_visits" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_page_visit_utm_source" ON "page_visits" USING btree ("utm_source");--> statement-breakpoint
CREATE INDEX "idx_page_visit_landing_page" ON "page_visits" USING btree ("landing_page");--> statement-breakpoint
CREATE INDEX "idx_guest_session_token" ON "guest_sessions" USING btree ("token");--> statement-breakpoint
CREATE INDEX "idx_guest_session_email" ON "guest_sessions" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_guest_session_expires_at" ON "guest_sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_guest_session_status" ON "guest_sessions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_guest_session_fingerprint" ON "guest_sessions" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "idx_guest_session_email_expires" ON "guest_sessions" USING btree ("email","expires_at");